# Generated by Django 2.2.5 on 2019-10-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_vacancy', models.CharField(max_length=250, unique=True, verbose_name='url')),
                ('title', models.CharField(max_length=250, verbose_name='vacancy')),
                ('description', models.TextField(blank=True, verbose_name='description vacancy')),
                ('company', models.CharField(blank=True, max_length=250, verbose_name='name company')),
                ('city', models.CharField(blank=True, max_length=250, verbose_name='city')),
                ('speciality', models.CharField(blank=True, max_length=250, verbose_name='speciality')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
