# Generated by Django 2.2.5 on 2019-10-01 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20191001_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='city'),
        ),

        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.CharField(max_length=250, unique=True, verbose_name='Адрес для поиска')),
                ('city',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.City', verbose_name='Город')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Site',
                                           verbose_name='Сайт для поиска')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.Specialty',
                                                 verbose_name='Специальность')),
                ],
            options={
                 'verbose_name_plural': 'Адресы для поиска',
                 'verbose_name': 'Адрес для поиска',
            },
        ),
    ]
