# Generated by Django 2.2.5 on 2019-10-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20191001_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_address',
            field=models.CharField(max_length=250, verbose_name='url_address'),
        ),
    ]
